In [2]:
import pandas as pd

df = pd.read_csv("accidents_weather_ca_merged.csv")
df.head()

,Start_Lat,Start_Lng,Start_Time,Severity,lat,lon,weather_main,weather_desc,temp_f,humidity,visibility,wind_speed,rain_1h
0,38.362831,-122.267197,2016-12-09 05:25:36,2,38.362831,-122.267197,Clear,clear sky,60.03,77,10000,6.91,0
1,34.022625,-118.156616,2016-07-12 10:55:04,2,34.022625,-118.156616,Clear,clear sky,65.93,40,10000,4.61,0
2,38.254620,-122.335907,2016-06-06 11:20:16,2,38.254620,-122.335907,Clear,clear sky,60.04,76,10000,6.91,0
3,38.003071,-121.337051,2016-12-17 09:25:08,2,38.003071,-121.337051,Clear,clear sky,58.32,78,10000,9.22,0
4,37.403236,-122.046913,2016-11-04 11:01:44,2,37.403236,-122.046913,Clear,clear sky,60.51,72,10000,8.05,0

In [3]:
X = df[[
    "temp_f",
    "humidity",
    "visibility",
    "wind_speed"
]]

y = df["Severity"]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

In [21]:
X_train.head()

     temp_f  humidity  visibility  wind_speed
5     60.49        71       10000        2.24
116   50.20        82       10000        1.77
45    67.12        30       10000       11.50
16    64.80        45       10000        4.61
462   50.14        28       10000        8.37

In [22]:
X_test.head()

     temp_f  humidity  visibility  wind_speed
361   65.97        42       10000        4.61
73    59.23        69       10000        8.05
374   58.44        71       10000        4.61
155   58.21        80       10000        4.61
104   56.80        77       10000        4.61

Multinomal Data

In [6]:
import pandas as pd

X_mnb = X.copy()

X_mnb["temp_f"] = pd.cut(X_mnb["temp_f"], bins=3, labels=[0,1,2])
X_mnb["humidity"] = pd.cut(X_mnb["humidity"], bins=3, labels=[0,1,2])
X_mnb["visibility"] = pd.cut(X_mnb["visibility"], bins=3, labels=[0,1,2])
X_mnb["wind_speed"] = pd.cut(X_mnb["wind_speed"], bins=3, labels=[0,1,2])
X_mnb = X_mnb.astype(int)

print(X_mnb)

     temp_f  humidity  visibility  wind_speed
0         2         2           1           1
1         2         0           1           0
2         2         2           1           1
3         1         2           1           1
4         2         2           1           1
..      ...       ...         ...         ...
495       2         0           1           1
496       1         2           1           2
497       2         2           1           1
498       2         0           1           0
499       2         2           1           1

[500 rows x 4 columns]

Gaussian Data

In [23]:
X_gnb = X.copy()
print(X_gnb)

     temp_f  humidity  visibility  wind_speed
0     60.03        77       10000        6.91
1     65.93        40       10000        4.61
2     60.04        76       10000        6.91
3     58.32        78       10000        9.22
4     60.51        72       10000        8.05
..      ...       ...         ...         ...
495   66.11        25       10000       10.00
496   58.03        78       10000       12.66
497   59.77        75       10000        8.05
498   66.07        37       10000        1.01
499   59.99        73       10000        8.05

[500 rows x 4 columns]

Bernoulli Data

In [8]:
X_bnb = (X > X.mean()).astype(int)
print(X_bnb)

     temp_f  humidity  visibility  wind_speed
0         1         1           0           0
1         1         0           0           0
2         1         1           0           0
3         0         1           0           1
4         1         1           0           1
..      ...       ...         ...         ...
495       1         0           0           1
496       0         1           0           1
497       1         1           0           1
498       1         0           0           0
499       1         1           0           1

[500 rows x 4 columns]

Train and split

In [9]:
X_train_mnb, X_test_mnb, y_train, y_test = train_test_split(X_mnb, y,test_size=0.3,random_state=42)

X_train_gnb, X_test_gnb, _, _ = train_test_split(X_gnb, y, test_size=0.3, random_state=42)

X_train_bnb, X_test_bnb, _, _ = train_test_split(X_bnb, y, test_size=0.3, random_state=42)

mnb split

In [10]:
X_train_mnb.head()

     temp_f  humidity  visibility  wind_speed
5         2         2           1           0
116       1         2           1           0
45        2         0           1           1
16        2         0           1           0
462       1         0           1           1

In [11]:
X_test_mnb.head()

     temp_f  humidity  visibility  wind_speed
361       2         0           1           0
73        2         2           1           1
374       1         2           1           0
155       1         2           1           0
104       1         2           1           0

gnb splt

In [12]:
X_train_gnb.head()

     temp_f  humidity  visibility  wind_speed
5     60.49        71       10000        2.24
116   50.20        82       10000        1.77
45    67.12        30       10000       11.50
16    64.80        45       10000        4.61
462   50.14        28       10000        8.37

In [13]:
X_test_gnb.head()

     temp_f  humidity  visibility  wind_speed
361   65.97        42       10000        4.61
73    59.23        69       10000        8.05
374   58.44        71       10000        4.61
155   58.21        80       10000        4.61
104   56.80        77       10000        4.61

bnb split

In [14]:
X_train_bnb.head()

     temp_f  humidity  visibility  wind_speed
5         1         1           0           0
116       0         1           0           0
45        1         0           0           1
16        1         0           0           0
462       0         0           0           1

In [15]:
X_test_bnb.head()

     temp_f  humidity  visibility  wind_speed
361       1         0           0           0
73        0         0           0           1
374       0         1           0           0
155       0         1           0           0
104       0         1           0           0

In [16]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Results mnb

In [17]:
mnb = MultinomialNB()
mnb.fit(X_train_mnb, y_train)

y_pred_mnb = mnb.predict(X_test_mnb)

print("Multinomial NB Accuracy:", accuracy_score(y_test, y_pred_mnb))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_mnb))

Multinomial NB Accuracy: 0.6333333333333333

Confusion Matrix:
 [[95  0  0]
 [54  0  0]
 [ 1  0  0]]

gnb results

In [18]:
gnb = GaussianNB()
gnb.fit(X_train_gnb, y_train)

y_pred_gnb = gnb.predict(X_test_gnb)

print("Gaussian NB Accuracy:", accuracy_score(y_test, y_pred_gnb))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_gnb))

Gaussian NB Accuracy: 0.5466666666666666

Confusion Matrix:
 [[76 19  0]
 [48  6  0]
 [ 1  0  0]]

bnb results

In [20]:
bnb = BernoulliNB()
bnb.fit(X_train_bnb, y_train)

y_pred_bnb = bnb.predict(X_test_bnb)

print("Bernoulli NB Accuracy:", accuracy_score(y_test, y_pred_bnb))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_bnb))

Bernoulli NB Accuracy: 0.6333333333333333

Confusion Matrix:
 [[95  0  0]
 [54  0  0]
 [ 1  0  0]]